# sudo: required
sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
python:
- "2.7"
addons:
  postgresql: 9.4
before_install:
- sh travis/before_install.sh
- export TERM=dumb
# script: ./gradlew jacocoTestReport coveralls && ./myriadeploy/launch_local_cluster && sleep 60 && python myria-web/appengine/myria_web_main.py && ./integration_tests.py
script:
- ./gradlew jacocoTestReport coveralls
- ls -l $(git rev-parse --show-toplevel)/build/libs/myria-0.1-all.jar
- ./myriadeploy/launch_local_cluster
- sleep 60
- python ~/myria-web/appengine/myria_web_main.py
- ./integration_tests.py
cache:
  directories:
  - $HOME/.gradle/caches

# encrypted AWS credentials for travis-ci IAM user under myria account
env:
  global:
    - secure: "djjW9ThHbafN5TUFGQi+mFkc4uQ8w6pQuSIT3kLOT8u78LuKSJ2LeO3kpqHbiIPwobJrwnFs8TrfWWro7HQVsrmPyJIxjgsu1oMGZYwacAsO47v+UuCBXYcu3JtjdRyub2+L65SNCh299eXDTxjPq0GkzZUHOHoj/lWYe/CCJgA="
    - secure: "CZ4RE0N0N/yeGnZZUf+ndN+vVzkLAgn2easCxExkOmvLqXmPNN9igKEaRAQ8sQ+YsAXuffyw2uxmo/paDUoVAcBpp/u/ZqdowdHHPcV13Upfqz70iQidsFU55zvF2CprmeHxNM1BLcbmVGY/tfeIrfosFSqb6gEOnSH/KfDsL6Y="
